pipeline {
    agent any
    stages {
        stage('CheckoutModule1') {
            steps {
                sh 'mkdir -p Module1'
                dir("Module1")
                        {
                            git branch: "master",
                                    credentialsId: 'ceranbsgithub',
                                    url: 'git@github.com:serdarceran/cucumber-java-selenium-webdriver-example.git'
                        }
            }
        }

        stage('CheckoutModule2') {
            steps {
                sh 'mkdir -p Module2'
                dir("Module2")
                        {
                            git branch: "master",
                                    credentialsId: 'ceranbsgithub',
                                    url: 'git@github.com:serdarceran/Kalah.git'
                        }
            }
        }
        stage('Test Module 1') {
            steps {
                dir("Module1")
                        {
                            withMaven(maven: 'maven') {
                                sh 'mvn clean test'
                            }
                        }
            }
        }
        stage('Build Module 2') {
            steps {
                dir("Module2")
                        {
                            withMaven(maven: 'maven') {
                                sh 'mvn clean package'
                                stash includes: 'target/*.jar', name: 'targetfiles'
                            }
                        }
            }
        }
    }
}