pipeline {
    agent any
    stages {
        stage('CheckoutModule1') {
            steps {
                sh 'mkdir -p Module1'
                dir("Module1")
                        {
                            git branch: "master",
                                    credentialsId: 'ceranbsgithub',
                                    url: 'git@github.com:serdarceran/cucumber-java-selenium-webdriver-example.git'
                        }
            }
        }

        stage('CheckoutModule2') {
            steps {
                sh 'mkdir -p Module2'
                dir("Module2")
                        {
                            git branch: "master",
                                    credentialsId: 'ceranbsgithub',
                                    url: 'git@github.com:serdarceran/Kalah.git'
                        }
            }
        }
    }
}